name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Install dependencies
      run: dotnet restore RoccoRelayServer/RoccoServe.SocketServer.sln
    - name: Build
      run: dotnet build RoccoRelayServer/RoccoServe.SocketServer.sln --configuration Release --no-restore
   
